gcc bigtest.c -o bigtest -lGLU -lGL -lglut
gcc cursor_test.c -o cursor_test -lGLU -lGL -lglut
gcc menu_test.c -o menu_test -lGLU -lGL -lglut
gcc over_test.c -o over_test -lGLU -lGL -lglut
gcc shape_test.c -o shape_test -lGLU -lGL -lglut
gcc test10.c -o test10 -lGLU -lGL -lglut
gcc test11.c -o test11 -lGLU -lGL -lglut
gcc test12.c -o test12 -lGLU -lGL -lglut
gcc test13.c -o test13 -lGLU -lGL -lglut
gcc test14.c -o test14 -lGLU -lGL -lglut
gcc test15.c -o test15 -lGLU -lGL -lglut
gcc test16.c -o test16 -lGLU -lGL -lglut
gcc test17.c -o test17 -lGLU -lGL -lglut
gcc test18.c -o test18 -lGLU -lGL -lglut
gcc test19.c -o test19 -lGLU -lGL -lglut
gcc test1.c -o test1 -lGLU -lGL -lglut
gcc test20.c -o test20 -lGLU -lGL -lglut
gcc test21.c -o test21 -lGLU -lGL -lglut
gcc test22.c -o test22 -lGLU -lGL -lglut
gcc test23.c -o test23 -lGLU -lGL -lglut
gcc test24.c -o test24 -lGLU -lGL -lglut
gcc test25.c -o test25 -lGLU -lGL -lglut
gcc test26.c -o test26 -lGLU -lGL -lglut
gcc test27.c -o test27 -lGLU -lGL -lglut
gcc test2.c -o test2 -lGLU -lGL -lglut
gcc test3.c -o test3 -lGLU -lGL -lglut
gcc test4.c -o test4 -lGLU -lGL -lglut
gcc test5.c -o test5 -lGLU -lGL -lglut
gcc test6.c -o test6 -lGLU -lGL -lglut
gcc test7.c -o test7 -lGLU -lGL -lglut
gcc test8.c -o test8 -lGLU -lGL -lglut
gcc test9.c -o test9 -lGLU -lGL -lglut
gcc timer_test.c -o timer_test -lGLU -lGL -lglut
